### ISSUE TITLE
Live TV is broken due to unimplemented startPTS_ in inputstream adaptive.

### ISSUE THREAD

**Issue by michaelarnauts** [michaelarnauts/plugin.video.vtm.go#1]
Live TV streams are currently broken. They start for a few seconds and stop.

**Comment by mediaminister** [comment]
I think I have a very experimental fix for live tv:
https://github.com/michaelarnauts/plugin.video.vtm.go/issues/16#issuecomment-517644562

**Comment by dagwieers** [comment]
The fix as made by @mediaminister as peak3d/inputstream.adaptive#298

**Comment by dagwieers** [comment]
This is now fixed in the just released **inputstream.adaptive v2.4.0**.
Thanks to @mediaminister and @peak3d !

**Comment by michaelarnauts** [comment]
There still was an issue, see https://github.com/peak3d/inputstream.adaptive/issues/322
I think we need a new release for that fix.

**Comment by mediaminister** [comment]
This issue was only present this weekend in the master branch, but is fixed now.

 v2.4.0 never got hit by this bug.

**Comment by dagwieers** [comment]
The biggest problem is that the new **inputstream.adaptive** does not ship to LibreELEC (and possibly other Linux/arm devices). I opened a forum thread for this on the LibreELEC forums, but no feedback yet. https://forum.libreelec.tv/thread/20300-how-to-get-a-newer-inputstream-adaptive-in-libreelec/?postID=127041#post127041

**Comment by peno64** [comment]
​I compiled the latest inputstream.adaptive for libreelec on raspberry pi myself.
You can find it here: http://users.telenet.be/peno/kodi/addons/inputstream.adaptive/

Note that this version is 2.4.0

And believe me, that is the latest version. So make sure that your addons aren't updated automatically or it will be overwritten by an auto update of the kodi addons​

**Comment by dagwieers** [comment]
@peno64 I tried it on LibreELEC 9.0.2 with Kodi 18.2 on Raspberry Pi 3B+ and it does not seem to work. I tried VTM GO, VRT NU and Netflix streams and none of them played.

**Comment by dagwieers** [comment]
After a reboot it *does* work well !

**Comment by peno64** [comment]
I work with kodi 18.4 on rpi 3 & 4
vrt nu and retrospect have no problems.
vtm go works, but after the first commercial and the vtm logo, so when the movie starts, you have to pause for a couple of seconds and then resume and then it plays without a problem, even when there are commercials later on.

**Comment by dagwieers** [comment]
@peno64 This is exactly what I have experienced. And that is a problem :-(

**Comment by peno64** [comment]
@dagwieers 
I tried a jenkins compilation of inputstream.adaptive 2.4.0 on kodi 18.4 on windows 64 bit and I also didn't have this problem with vtm go then. It just plays without any problem.
Strange that it only occurs with rpi.
Strange also that a pause of a couple of seconds works-around the problem.

**Comment by dagwieers** [comment]
@peno64 See my update in my previous comment ;-)

**Comment by mediaminister** [comment]
If you compile the Leia branch, you don't have support for Periods at all.
This is unreleased stuff only available in master branch. Only available as a binary in Jenkins.

**Comment by dagwieers** [comment]
@mediaminister In that case we have to report this behaviour on Raspberry Pi to **inputstream.adaptive**. But I am not sure if the master branch is intended to work as-is on Kodi 18.

**Comment by peno64** [comment]
@mediaminister 
@dagwieers 
I am willing to compile another branch is you want. Maybe a new branch op the Leia branch can be made and the period development can be merged into it? Than I can compile this branch.
If so, please let me know the http command to get that branch

**Comment by dagwieers** [comment]
@peno64 It is probably better that we report on our experience with the master branch running on Leia. I am just confused about how these branches are being maintained (what is going where and how they differ). I assumed the Leia and Matrix branches were needed for functional differences (wrt. Kodi), but it appears some PRs are only added to the Matrix branch (probably for wider testing). It is unclear to me if some of these PRs are going to be backported to Leia or not.

cc @peak3d

**Comment by dagwieers** [comment]
@peno64 I also noticed that subtitles no longer work with your build. There are none available in Kodi to select.

**Comment by dagwieers** [comment]
I can confirm that a reboot is required to make this work. I experienced it on my other devices as well.

**Comment by peno64** [comment]
@dagwieers 
Yes I also noticed that a reboot is required after updating inputstream.adaptive.
I guess this comes because it includes binaries which are loaded in memory the first time they are used and they stay there even when replaced with a newer version and that until the system is rebooted. Luckly the system allows to replace those binaries which are still in memory. Windows is not that easy in this.

**Comment by dagwieers** [comment]
@peno64 The difference here is that normal playback *fails* to work until the system is rebooted, while you would expect playback to work as before until you reboot.

**Comment by michaelarnauts** [comment]
@peno64 do you know if your build works for all arm devices (armv6 or armv7?) or only for raspberry pi?

**Comment by peno64** [comment]
@michaelarnauts 
I don't know. I only have a pi3 & pi4
The same build works for both devices although they are different processors. So there is a chance it also works on other arm devices.

I compiled this on a raspbarian linux on the pi.
I also tried to compile with an ubuntu linux on the pi but then the binaries are not working on the pi's. I guess ubuntu depends or links on libraries not available or compatible with the libreelec linux os. So if the other devices are more ubuntu os related systems (I know libreelec is not) then my compile will probably not work.
I can make the ubunu build also available if you want.

**Comment by michaelarnauts** [comment]
I have a compiled build for OSMC here, not sure if this is working on all versions. I had to copy the files to `/usr/lib/kodi/addons/inputstream.adaptive/`.

[inputstream.adaptive.zip](https://github.com/michaelarnauts/plugin.video.vtm.go/files/3720563/inputstream.adaptive.zip)

**Comment by michaelarnauts** [comment]
I've bundled all inputstream.adaptive issues that are already fixed upstream, but not yet released in issue #101.
