### ISSUE TITLE
Something is not right with the new 0.9.1 version

### ISSUE THREAD

**Issue by peno64** [michaelarnauts/plugin.video.vtm.go#106]
When I install this version and start the vtm go addon, it does not start the addon but it shows a files folder. See printscreen
![screenshot000](https://user-images.githubusercontent.com/32430988/66948988-013adf80-f056-11e9-8804-d879c070d738.png)

Installing the 0.9.0 version again gives again the addon

**Comment by peno64** [comment]
Downloading and installing the master version does work however.
![plugin video vtm go-master](https://user-images.githubusercontent.com/32430988/66949323-976f0580-f056-11e9-9cb2-4bb755aaea2d.jpg)

So the problem is only in the release 0.9.1 zip file

**Comment by michaelarnauts** [comment]
I see what went wrong. The main entry points weren't packaged.

**Comment by peno64** [comment]
Looking good now.
