### ISSUE TITLE
On-demand always starts after last advertisement

### ISSUE THREAD

**Issue by skycamel** [michaelarnauts/plugin.video.vtm.go#113]
**Describe the bug**
The demanded episode will start with the opening generic but then immediately continue with last part after last advertisement

**To Reproduce**
1.Go in to catalog and select on-demand episode to watch (Alloo bij de wegpolitie)
2. Season 3 ep.3
3.

**Expected behavior**
Should start from beginning of episode and not skip to last part after advertisement
**Screenshots**

**System**
 - Addon version:0.9.1
 - Kodi version:18.4
 - Inputstream adaptive version: 2.4.2.1
 - Operating System:  LibreElec 
RPI 3

**Additional context**

**Comment by michaelarnauts** [comment]
Are you sure you have an updated inputstream adaptive with the required fixes?

**Comment by skycamel** [comment]
If you mean if I did build my own inputstream adaptive as per peno64 instructions, no I didn't.
But I do have the latest version 2.4.2.1 available on Kodi.
Maybe interesting to know, I can watch the same episode (and others) without any issues using Stievie on Kodi, it will just skip every advertising after a few seconds and continue the video.
Downside with Stievie (among others) you can only go back 7 days.

**Comment by michaelarnauts** [comment]
The version from Kodi doesn't work. Please take some time to read the README and the page on the wiki.

**Comment by skycamel** [comment]
Sorry, I got mislead by some comments in a forum whereby they were referring to 2.4.2.1 as the latest and working. I downloaded the compiled version of peno64 and working now.
But there's still an issue when starting any VOD, it will pause, skip back, start again pause start again no audio and then after 15 sec of all of this working fine.
Cheers,
Luc
