### ISSUE TITLE
Add a per-channel program listing

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#120]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a per-channel program listing as part of the existing **Channels** listing.

**Describe the solution you'd like**
It is nice if users can add the single channel entries to their favorites to make a collection of channels regardless of the add-on they belong to and have the VOD content and live TV behind a single bookmark. (Babysit and grandmother proof!)

**Comment by michaelarnauts** [comment]
Now that I've cached the metadata of the full catalog, this is actually possible by looping over the full listing and filtering out by studio.

**Comment by dagwieers** [comment]
It is more convenient to see all programs in the same listing, rather than a sub-listing.

**Comment by michaelarnauts** [comment]
> It is more convenient to see all programs in the same listing, rather than a sub-listing.

I don't agree, since the submenu can be properly sorted and has a better content type. Semantically, this is more correct.

**Comment by dagwieers** [comment]
In that case mixing TV shows and Movies in the A-Z listing and My List is a problem too.
That is, if correctness comes before convenience.
