### ISSUE TITLE
Availability now comes at the end of plot

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#124]
**Describe the bug**
Since the availability now comes at the end of the plot, it is no longer visible if the plot fills the available screen estate.

Our kids couldn't finish a movie today, because it disappeared and they didn't know because the availability was off screen.

I don't know when this changed, I remember it to be at the top before, except if it availability was more than a year or something.

**Comment by michaelarnauts** [comment]
I had moved it to the bottom since it was looking out of place on my default skin (Arctic Zephyr 2) where the plot view was scrolling anyway. It seems that on the default skin (Estuary), it doesn't scroll and so isn't visible. I moved it back to the top.

**Comment by dagwieers** [comment]
@michaelarnauts There is an option in Estuary to enable scrolling (we have it enabled), but even then the scrolling only starts after about 8 seconds, so it doesn't hurt when scrolling or reading.

**Comment by michaelarnauts** [comment]
Aha, you are right. It's even activated by default. I guess I never waited long enough to see this :)

**Comment by dagwieers** [comment]
I wasn't sure if it was activated on default, I trusted you more than my memory ;-)
