### ISSUE TITLE
VTM GO now has the notion of profiles

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#129]
**Is your feature request related to a problem? Please describe.**
It appears VTM GO is taking the same route as Netflix to first select who is watching. You can create multiple profiles and select your profile as a viewer.

**Describe the solution you'd like**
The Netflix add-on has a smart way of dealing with this. Show the profiles as the first screen unless the user has selected which profile is to be used for this device in the settings.

This is the best of both worlds, as it allows you to select a specific profile for your Kodi profile.

**Additional context**
Check the Netflix add-on, you can select your preferred profile using the context menu.

**Comment by michaelarnauts** [comment]
Fixed in #132

**Comment by dagwieers** [comment]
I think it is confusing that the new menu-item states:
> Switch Profile (**Dag**)

**Comment by dagwieers** [comment]
It works well, although I think we still need a way to jump directly to a configured profile (without a way to switch to another). This would again work as Kids zone. Look at the Netflix add-on how they do this.

**Comment by michaelarnauts** [comment]
You mean to select a profile at startup, or use one that you configure in the settings?

And without the switch item in the menu then?

**Comment by michaelarnauts** [comment]
I made #133 for the follow-up
