### ISSUE TITLE
HTTP 426: Upgrade required

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#131]
**Describe the bug**
I just received this error when opening a program that was saved as a favorite.
But I seem to get it now on every request.

**Expected behavior**
It works as before.

**Screenshots**
```
2020-01-23 00:56:24.236 T:1290826624   ERROR: GetDirectory - Error getting plugin://plugin.video.vtm.go/catalog
2020-01-23 00:56:24.240 T:1937588800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/catalog) failed
2020-01-23 00:56:26.869 T:1257255808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error 426.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/plugin.py", line 8, in <module>
                                                plugin.run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 193, in run
                                                routing.run(params)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 25, in show_channels
                                                Channels(kodi).show_channels()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/channels.py", line 28, in show_channels
                                                channel_infos = self._vtm_go.get_live_channels()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 380, in get_live_channels
                                                response = self._get_url('/%s/live' % self._mode())
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 679, in _get_url
                                                raise Exception('Error %s.' % response.status_code)
                                            Exception: Error 426.
                                            -->End of Python script error report<--
2020-01-23 00:56:27.082 T:1290826624   ERROR: GetDirectory - Error getting plugin://plugin.video.vtm.go/channels
2020-01-23 00:56:27.086 T:1937588800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/channels) failed
```

**System**
 - Addon version: 0.9.2
 - Kodi version: 18.5
 - Inputstream adaptive version: 2.4.2
 - Operating System: (Windows / Mac OS / Android / LibreElec / OSMC / ...) LibreELEC v9.2.0
 - Special Hardware: (RPI / Vero4K+ / ...) RPI3

**Comment by wvalcke** [comment]
I used the addon master branch version, and i have the exact same problem.
Using Kodi 18.5, raspberry pi 4, Inputstream adaptive 2.4.2

**Comment by michaelarnauts** [comment]
The addon is using an old API version that was probably just outphased.

**Comment by Mich-b** [comment]
Modifying two files fixed it:

### vtmgo.py
1) replace `https://api.vtmgo.be` with `https://lfvp-api.dpgmedia.net`
2) replace    ```
_HEADERS = {
        'x-app-version': '5',
        'x-persgroep-mobile-app': 'true',
        'x-persgroep-os': 'android',
        'x-persgroep-os-version': '23',
        'User-Agent': 'VTMGO/6.8.2 (be.vmma.vtm.zenderapp; build:11215; Android 23) okhttp/3.14.2'
    }
```  
with      
```
_HEADERS = {
        'x-app-version': '8',
        'x-dpp-profile': 'XXXXXXXXXXXXXXXXX',
        'User-Agent': 'LFVP iOS/6.11.3 (be.vmma.vtm.zenderapp; build:2576; iOS 13.3.0) RxSwift/5.0.0'
    }
```
You should replace XXXXXXXXXXXX with an identifier (looks like a guid). I am hesitant to publish mine since I'm not yet sure what it means. 

### vtmgoauth.py
login function in vtmgoauth.py:
```
    def _login(self):
        """ Executes a login and returns the JSON Web Token.
        :rtype str
        """
        # Create new session object. This keeps the cookies across requests.
        session = requests.sessions.session()

        # Get login form. This sets some cookies we need.
        session.get('https://login2.vtm.be/authorize', params={
            'redirect_uri': 'vtmgo://callback/oidc',
            'client_id': 'vtm-go-ios',
            'response_type': 'id_token',
            'state': self._generate_random_id(22),
            'nonce': self._generate_random_id(22),
            'scope': 'openid profile'
        }, headers={
            'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Mobile Safari/537.36'
        }, proxies=self._proxies)

        # Now, send the login details. We will be redirected to vtmgo:// when we succeed. We then can extract an authorizationCode that we need to continue.
        try:
            response = session.post('https://login2.vtm.be/login/emailfirst/password?client_id=vtm-go-ios', data={                 'userName': self.username,
                'password': self.password,
                'jsEnabled': 'true',
            }, proxies=self._proxies)

            if 'errorBlock-OIDC-004' in response.text:  # E-mailadres is niet gekend.
                raise InvalidLoginException()

            if 'errorBlock-OIDC-003' in response.text:  # Wachtwoord is niet correct.
                raise InvalidLoginException()

            raise LoginErrorException(code=100)  # Unknown error while logging in

        except requests.exceptions.InvalidSchema as e:
            # I found no other way to get this url then by parsing the Exception message. :(
            import re
            matches = re.search(r"id_token=([^']+)", str(e))
            if matches:
                id_token = matches.group(1)
            else:
                raise LoginErrorException(code=101)  # Could not extract authentication id_token

        # Okay, final stage. We now need to use our id_token to get a valid JWT.
        response = session.post('https://lfvp-api.dpgmedia.net/authorize/idToken', json={
            'pipIdToken': id_token
        }, headers={
            'x-app-version': '8',
            'User-Agent': 'LFVP iOS/6.11.3 (be.vmma.vtm.zenderapp; build:2576; iOS 13.3.0) RxSwift/5.0.0'
        }, proxies=self._proxies)
        print(response.text)
        tokens = json.loads(response.text)

        self._token = tokens.get('jsonWebToken')
        # self._name = tokens.get('name')
        # self._accountId = tokens.get('accountId')

        return self._token

```

**Comment by michaelarnauts** [comment]
@Mich-b The `x-dpp-profile` is probably the profile that you want to use. It seems the Android app is using different headers compared with the iOS app.

Can you check out my merge request if that code works for you?

**Comment by Mich-b** [comment]
@michaelarnauts , installed the new-api branch and tested it => works for me! Thanks.

**Comment by dagwieers** [comment]
I tested the new master branch and everything is working well. Creating new profiles can only be performed on vtmgo.be, which is fine I guess.
