### ISSUE TITLE
Profile improvements/issues braindump

### ISSUE THREAD

**Issue by michaelarnauts** [michaelarnauts/plugin.video.vtm.go#133]
Profiles work, but there are a few remarks:

* Handle the case when you have no profile on your account
* Handle the case when your settings has no profile selected and you open the add-on, actually, the onboarding of new users could be better.
* When switching profiles, and hitting back, you go back to the same menu.
* Allow to set your profile from the settings with an option to ask your profile at startup.
* We get the profile "color" so we might want to do something with that. There are no images however like with Netflix.

**Comment by michaelarnauts** [comment]
@dagwieers Just found out that only one normal profile is allowed, and up to 4 kids profiles.

**Comment by dagwieers** [comment]
Correct, I could only add kid profiles. In practice people will only create one for the kids on Kodi IMO.

**Comment by michaelarnauts** [comment]
I was hoping this was like Netflix, where you could have multiple full profiles with individual statuses.

I have almost a branch ready that implements above changed.
