### ISSUE TITLE
Allow rewinding during a Live TV Stream

### ISSUE THREAD

**Issue by Dominiquedb** [michaelarnauts/plugin.video.vtm.go#136]
Would it be possible to add a rewind feature for livestreams?
In the retrospect addon we have the ability to rewind 15 minutes at the beginning of livestreams, so lets say I turn on my tv at 19.10h I can rewind to 19.00h and watch the news on vtm from the beginning.

Because of this I'm currently watching dpg media livestreams on the retrospect addon and catchup tv on your addon

**Comment by michaelarnauts** [comment]
@dagwieers is this something you have tried with vrt.nu? When opening the live stream in the android app, it also allows to go back about 20 minutes in time. I assume this is something inputstream.adaptive should be able to handle?

**Comment by michaelarnauts** [comment]
Just tried this, and it actually works fine on vrt.nu addon and on the Stievie channels in retrospect.

**Comment by michaelarnauts** [comment]
@Dominiquedb I don't seem to be getting the playlist data for older video segments. I also noticed that this is not possible on the vtm go website, or the mobile app, so I guess this is something that isn't supported by VTM GO.

**Comment by Dominiquedb** [comment]
Okay, too bad, would have been nice

**Comment by mediaminister** [comment]
VRT NU has a livestream cache of 24 hours. It is used for the airdate api when there is no on demand stream, for instance to rewatch "Winterbeelden" or "Radio 2 op één".

**Comment by michaelarnauts** [comment]
https://customerservice.vtmgo.be/hc/nl/articles/360001282118-Ik-ben-net-te-laat-voor-een-live-programma-kan-ik-inpikken-vanaf-het-begin-

Gaat dus helaas niet lukken.
