### ISSUE TITLE
Works without login

### ISSUE THREAD

**Issue by Dominiquedb** [michaelarnauts/plugin.video.vtm.go#137]
I just noticed that the addon works even without a login and password. Not sure if this is unintentional, but just thought I could let you know.

**Comment by michaelarnauts** [comment]
I've also noticed this, but it's against the terms of use of VTM GO, so you should better log in. You also get the benefit of having access to your started items (My List).

**Comment by Dominiquedb** [comment]
I use my login, no reason not to
