### ISSUE TITLE
VTM GO's live streams on the kodi addon don't work

### ISSUE THREAD

**Issue by reneverlinden** [michaelarnauts/plugin.video.vtm.go#147]
**Describe the bug**
I work with kodi 18.5 , Leia and Libreleec 19.2.0 on rpi 4B 2GB , directly connected with the modem via ethernetcable
vrt nu and retrospect have no problems, the live streams of the channels work both correctly,
all the items, movies and programs of the vtm go-addon  perform perfectly, excepted  the livestreams of all the channels (VTM,Q2,CAZ...); when I select one of these channels ,say VTM Live,   only the tittle of the live program appears on the right upper corner of the screen and after a couple of seconds the whole system (kodi) reboots  , 
my question is : what could be the reason of this ?

**Comment by dagwieers** [comment]
The only reason I can think of is an issue with **inputstream.adaptive** (or Kodi).
What version of **VTM GO add-on** and **inputstream.adaptive** are you using?

Can you make a screenshot of the inputstreamhelper
![64066699-61e49900-cc1d-11e9-82ea-bd4117dfbd7c](https://user-images.githubusercontent.com/388198/75385999-2c292000-58e1-11ea-91b1-638b8a148c6a.png)
 info pane? It should look like this:

**Comment by reneverlinden** [comment]
Dear,

In attachement you’ll find the information about the InputStream Helper in pdf-format

Thanks,

René Verlinden

Verzonden vanuit Mail voor Windows 10

Van: Dag Wieers
Verzonden: woensdag 26 februari 2020 21:44
Aan: michaelarnauts/plugin.video.vtm.go
CC: reneverlinden; Author
Onderwerp: Re: [michaelarnauts/plugin.video.vtm.go] VTM GO's live streams on thekodi addon don't work (#147)

The only reason I can think of is an issue with inputstream.adaptive (or Kodi).
What version of VTM GO add-on and inputstream.adaptive are you using?
Can you make a screenshot of the inputstreamhelper

info pane? It should look like this:

**Comment by dagwieers** [comment]
@reneverlinden You need to log into GitHub and add it to your comment. Replying to mails doesn't work for attachments apparently.

**Comment by reneverlinden** [comment]
Here is the information about the InputStream Helper :

Kodi Information
	
	Kodi-Version 18-5
	Kodi-Architecture Linux/arm

Inputstream Adaptive

	Inputstream Helper version: 0.4.3
	Inputstream Adaptive version :2.4.2.1

Widevine

          Widevine-version : 4.10.1610.6 ( last updated 23/2/2020)
	 Chrome OS-version : 12607.82.0

**Comment by dagwieers** [comment]
@reneverlinden Can we know what fixed your problem?

**Comment by reneverlinden** [comment]
OK, I 'll wait and... see !
I'll tell you and  I 'll contact you when there is  an update version  4.2.4.3 of InputStream Adaptive.

Thanks!

**Comment by dagwieers** [comment]
We expect the **inputstream.adaptive** v2.4.3 update to hit LibreELEC in the coming days.
https://github.com/LibreELEC/LibreELEC.tv/pull/4226

**Comment by michaelarnauts** [comment]
@reneverlinden you definitely need inputstream 2.4.3 for this addon to work. It should by now be available in your repositories, unless you are running osmc.

**Comment by reneverlinden** [comment]
Thanks for the update of Inputstream Adaptive 2.4.3 and the update of VTMG I've recieved yesterday.
The livestreams of VTM GO- plugin don't work even with the new updates. When I select VTM Live, Q2 live or other livestreams,  the tittle of the live program still appears on the right upper corner on the screen and immediately disappears. The only difference with version 2.4.2 is that the system doesn't reboot ,  but the video won't start. And a side-effect of the new update is that all the livestreams of retrospect, stievie and regio tv don't work in version 2.4.3, but work  perfectly in the former version of Inputstream Adaptive 2.4.2.1.

**Comment by dagwieers** [comment]
@reneverlinden When updating **inputstream.adaptive** you need to restart Kodi (or reboot your system) otherwise the new **inputstream.adaptive** is not activated. That is why things are now failing all over the board.

So please reboot your system, and try again.

**Comment by reneverlinden** [comment]
Indeed, yesterday I had restarted Kodi, but this day I 've rebooted  Kodi and suddenly all the Livestreams and videos on demand of VTMGO  work perfectly, even better than those of Retrospect and Stievie ! Thanks  mr Dagwieers , thanks mr arnauts , with the inputstream Adaptive 2.4 you' ve done a good job!

**Comment by reneverlinden** [comment]
Earlier I have add the livestreams of VTM GO to My Favourites and when I select each of them in this menu of Favourites  now the Livestrems perform well as I 've said , and all the items A-Z , Catalogue, Search in VTM GO etc  work good too , but when I select the item "Channels" a message of error occurs : "ERROR , controll the log file".   Could you say what 's the reason of this?
Thanks

**Comment by reneverlinden** [comment]
The problem of the former comment seems be solved by re-installing the addon VTM GO and by choosing the latest version of  VTM GO 's updates.
Thanks

**Comment by dagwieers** [comment]
Yes, this was reported in #150 and fixed in #151.

**Comment by reneverlinden** [comment]
I 'll close this issue #147
