### ISSUE TITLE
channels menu not working

### ISSUE THREAD

**Issue by Dominiquedb** [michaelarnauts/plugin.video.vtm.go#150]
when clicking channels it no longer opens the channels menu

1. open addon
2.click channels

**Expected behavior**
I expected the channels menu to open, giving me access to live streams and the tv guide

**Screenshots**
![Screenshot_20200302-145924](https://user-images.githubusercontent.com/60631056/75686613-d667c580-5c9c-11ea-8ded-9864bbbd6f55.png)

**System**
 - Addon version: 0.9.4
 - Kodi version: 18.5 / 18.6
 - Inputstream adaptive version: 0.4.3
 - Operating System: android / android tv / ubuntu

**Additional context**
all the favourite links I made before from the channels menu still work perfectly fine, like all the live streams and the vtm tv guide

**Comment by michaelarnauts** [comment]
Can you please include the Kodi logs?

**Comment by mediaminister** [comment]
Fixed it, the launch of CAZ2 broke the channel menu.
@Dominiquedb Please test 
[plugin.video.vtm.go-1.0.0-livechannels-1edc610.zip](https://github.com/michaelarnauts/plugin.video.vtm.go/files/4277124/plugin.video.vtm.go-1.0.0-livechannels-1edc610.zip)

**Comment by Dominiquedb** [comment]
It works

**Comment by mediaminister** [comment]
Thanks for confirming, I also added the new channel CAZ 2:
[plugin.video.vtm.go-1.0.0-livechannels-7bb507a.zip](https://github.com/michaelarnauts/plugin.video.vtm.go/files/4277321/plugin.video.vtm.go-1.0.0-livechannels-7bb507a.zip)
