### ISSUE TITLE
Studio icons in Kodi are missing/ugly

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#17]
The icons in **resource.images.studios.white** and **resource.images.studios.coloured** for Medialaan brands are either missing or outdated.

It could be useful to have them, i.e. they work out-of-the-box with YouTube support, and could be useful in the future for other content as well (if we would have this information per program).

**Comment by michaelarnauts** [comment]
The API contains an url to a channel icon for vod content, i don't see a textual representation of the channel.

```
        "channelLogoUrl": "https://api.vtmgo.be/static/images/logos/vitaya-412f405c5dbc13e88844d8ba20e2e611.png",
```

**Comment by dagwieers** [comment]
Right, but I cannot use those for the YouTube channels, whereas if they were part of the Studios icons, they would be available. Currently Estuary has a deficiency and so only the TV shows content view can display studio icons, unless you patch it. The fix will be in Kodi Matrix as they don't backport visual improvements.

**Comment by mediaminister** [comment]
I created pull request with the logos.
https://github.com/XBMC-Addons/resource.images.studios.white/pull/24
https://github.com/XBMC-Addons/resource.images.studios.coloured/pull/25

**Comment by dagwieers** [comment]
This should be fixed and released now. To be tested.

**Comment by dagwieers** [comment]
This appears to be fixed. The Youtube menu shows proper icons now.
