### ISSUE TITLE
Add an alphabetic overview of all programs

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#18]
Online there is a **Catalogus** » **Alle Genres** entry that shows all programs alphabetically (or at least semi-alphabetically). It would be nice if the add-on could offer the same listing (properly sorted in this case).

**Comment by dagwieers** [comment]
It appears that the website is also looping over the different genres, and not actually merging the content. So we definitely could do the same, but better.

**Comment by michaelarnauts** [comment]
It's easy. You need to include the "All genres" entry manually and call `get_items()` without specifying a category. This will make a call to the API without a filter. The code is already there to do this.
