### ISSUE TITLE
Ordering is messy

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#23]
So I am going to open an issue so we can collect the errors in ordering one-by-one.

**Comment by dagwieers** [comment]
When using SORT_METHOD_UNSORTED on the seasons-listing of **Married with children** you get:
- Season 8
- Season 1
- Season 9
- Season 7

**Comment by dagwieers** [comment]
When using SORT_METHOD_UNSORTED on the episodes-listing of **Maya de bij** you get:
- Aflevering 32
- Aflevering 1
- Aflevering 2

Presumably because it lists the last broadcasted episode first ?

Ordering by episode makes the most sense, as it shows the episode number. (In this case the duration is not being shown, but that doesn't matter because it is in the MediaInfo box at the lower-right anyway)

**Comment by michaelarnauts** [comment]
* The view of the seasons should be sorted by Title/Label. This also happens in the mobile app.
* I don't see a wrong order in Maya de bij with unsorted. Season 1 starts with "De fles van willy" (1x1) and ends with "De lieve wesp" (1x32).

**Comment by michaelarnauts** [comment]
For the A-Z view, you probably want "SORT_METHOD_LABEL_IGNORE_FOLDERS". This sorts by label, and puts the folders in between. 
I will adapt your merge request :)

**Comment by dagwieers** [comment]
> The view of the seasons should be sorted by Title/Label. This also happens in the mobile app.

What happens  wrt. Season 10 ?

> I don't see a wrong order in Maya de bij with unsorted. Season 1 starts with "De fles van willy" (1x1) and ends with "De lieve wesp" (1x32).

Weird, I assumed maybe 1x32 was broadcasted in the meantime (putting it back at the end of the list) but I still see the list start with "De lieve wesp" (1x32) before all other episodes when using UNSORTED.

> For the A-Z view, you probably want "SORT_METHOD_LABEL_IGNORE_FOLDERS".

We deliberately did not use SORT_METHOD_LABEL_IGNORE_FOLDERS for VRT NU, but I cannot remember why that was precisely.

*It may be because it orders ignoring The/De etc. and since we cannot guarantee this type of ordering for all listings we didn't want to add to the confusion. Not sure if that was the main reason though.*

**Comment by dagwieers** [comment]
Also, because there is no means to order in reverse order and this is what VRT NU is doing for some programs (newest first) we do have to sort some views ourselves and fall back to SORT_METHOD_UNSORTED.

**Comment by dagwieers** [comment]
> > I don't see a wrong order in Maya de bij with unsorted. Season 1 starts with "De fles van willy" (1x1) and ends with "De lieve wesp" (1x32).
> 
> Weird, I assumed maybe 1x32 was broadcasted in the meantime (putting it back at the end of the list) but I still see the list start with "De lieve wesp" (1x32) before all other episodes when using UNSORTED.

Beware that due to a bug in Kodi, going to the Default ordering (SORT_METHOD_UNSORTED) doesn't reorder the listing, you have to exit the screen and go back to see the "Default" ordering in action. Maybe that has been the cause of what you saw. We ought to fix this in Kodi...

**Comment by michaelarnauts** [comment]
Sorry, didn't notice your remarks.
* I think Season 10 is sorted after Season 9. In Famillie, I can see Season 1991 is sorted after Season 28.
* I never liked sorting that tried to magically filter out *The* or *De*. What about *Het*, or *Een*... It is never consistent. I just prefer the full name.
* I'm aware of the bug that going back to default doesn't revert the sorting. But it's sorted by episode now, so it should be correct nevertheless.
