### ISSUE TITLE
Seeking is not possible

### ISSUE THREAD

**Issue by peno64** [michaelarnauts/plugin.video.vtm.go#28]
In all addons I have used in kodi it is possible to move foreward in the stream bij pressing the right button. Is there a reason why this is not possible in this addon?

**Comment by michaelarnauts** [comment]
I've also noticed this. I assume this has to do with the missing Periods implementation of inputstream adaptive.

**Comment by dagwieers** [comment]
Relates to #8

**Comment by dagwieers** [comment]
With the latest master build from **inputstream.adaptive** seeking works as expected !

**Comment by michaelarnauts** [comment]
I don't know about arm builds, but x64 windows and Linux builds are done for every commit on Jenkins.

**Comment by peno64** [comment]
I tried this on windows x64 with the latest kodi 19 and inputstream.adaptive 2.5.0 and I still can't seek ...

**Comment by michaelarnauts** [comment]
Are you sure you got the right one? It should be 2.4.0 from the latest builds.

1. Go to https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/activity?branch=master
2. Click the latest commit 
3. Click artifacts at the top right
4. Download the right build.

**Comment by mediaminister** [comment]
If we require full seeking support for version 1.0.0, we should require Kodi 19 as the minimum version because we need the new IChapter interface. Kodi 19 is not released yet.

**Comment by michaelarnauts** [comment]
I just tried seeking on Kodi 18 and it worked just fine. What isn't supposed to be working then?

**Comment by mediaminister** [comment]
You're right, I was mistaken because I tested with an older InputStream Adaptive, but with the last commit in master branch seeking works fine.
To skip periods you will need Kodi 19 with the IChapter interface

**Comment by michaelarnauts** [comment]
I've bundled all inputstream.adaptive issues that are already fixed upstream, but not yet released in issue #101.
