### ISSUE TITLE
Add TV Guide

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#37]
Since we have EPG information, we could add a TV Guide, just like the VRT NU add-on.

**Comment by michaelarnauts** [comment]
I think we only have the next shows, not a real EPG...

**Comment by dagwieers** [comment]
Alright, I mixed the TV Guide from VTM.be with VTM GO. Apparently VTM GO does not have real EPG information at all...

**Comment by michaelarnauts** [comment]
I will reopen this. It seems the website uses an api at `https://vtm.be/tv-gids/api/v2/broadcasts/2019-08-22` to get an EPG. At first sight, this EPG also includes the ID's that might be usable to start a stream.

Example program data:
```
{
"uuid":"21867b5c-2616-4753-ae90-148ee9262ab1",
"channelUuid":"d8659669-b964-414c-aa9c-e31d8d15696b",
"from":1566532500000,
"to":1566534000000,
"title":"Dinotrux Supercharged",
"live":false,
"rerun":true,
"legalIcons":[
],
"duration":1320,
"synopsis":null,
"imageUrl":"https://images1.persgroep.net/rcs/0S5sCWdWQjI8ozereiM_Q_gOSto/diocontent/147372918/_fill/720/405?appId=da11c75db9b73ea0f41f0cd0da631c71",
"playableType":"episodes",
"genre":null,
"subGenres":[
],
"tip":false,
"fromIso":"2019-08-23T03:55:00",
"toIso":"2019-08-23T04:20:00"
},
```

**Comment by dagwieers** [comment]
And a channelUuid ! This opens up the possibility to link programs to channels.

**Comment by michaelarnauts** [comment]
The item is already inside a `channel` tag, so we know what channel the program is on :)
