### ISSUE TITLE
Ability to exclude/filter programs

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#38]
One of the issues with the existing VTM GO categories is that they are overly broad.

In our household I would like the children to watch the children offerings, but those currently include a list of things we don't want to children to be exposed to. The different VLOGS and reality shows are of a very low quality, tend to voyeurism and seem to promote a materialistic lifestyle.

The discussion now is to either remove VTM GO completely, or filter what the children are allowed to watch. Even if there was a PG-rating type of selection, it would probably not match our standards either.

**Comment by dagwieers** [comment]
For me the ideal situation would be that I could select "Hide" on programs, and they would get filtered out of the Category-listings (like Kids). That way new programs would become available automatically, while known unwanted programs are excluded in that view.

The current listing (https://vtm.be/vtmgo/catalogus?filter=kids) consists of the following we definitely do not want for a 6yo and 8yo:
- Beestig
- Benidorm bastards
- De kotmadam
- LousLouise
- Safety First
- Sara
- The nanny
- Wauters vs Waes
- Battle of the Tiktokkers
- Cavegirl
- De buurtpolitie
- Het lichaam van Coppens
- Spellkeepers
- The Greenhouse
- Vloglab
- Vloglab Beach
- Vloglab Love
- Vloglab Winter

The Teens category does not contain the above, which would probably make more sense. Ideally VTM GO ought to have a better segregated "Toddlers", "Kids", "Teens" sections, but still parents may want to hide certain content.

**Comment by michaelarnauts** [comment]
Hmm, not sure this belongs in the addon. Kids are smart enough these days to find out how to "unlock" these programs anyway. You would also have to restrict the live stream for example.

I do agree however that some content you've mentioned should not be in the Kids category, but that concern should perhaps be better addressed to medialaan.

I think creating a "whitelist" by adding bookmarks, maybe with https://kodi.wiki/view/Add-on:Super_Favourites is a better way. I've bookmarked a selection of programs my kids like to watch (from VRT NU).

**Comment by dagwieers** [comment]
The kids won't be able to unlock this as they have a quite restricted profile where they cannot start the addon and only access specific functionality through Kodi Favourites.

The problem of creating individual Favourites for specific programs (whitelisting) is not a good option as newer programs would not automatically appear and would require me to look for new programs in order to add them, whereas hiding newer programs from all views would be much easier. (We tend to know what our children are watching, but can't control it all the time).

**Comment by dagwieers** [comment]
The website now has a "Kids zone" which does not include the programs designed for adults, the VTM GO addon does not have this (yet), but I expect this will come as well.

**Comment by michaelarnauts** [comment]
The app also has a kids mode. I assumed that it would just use the kids category, but that's probably incorrect. I need to check what API call the kids mode does.

**Comment by dagwieers** [comment]
That could be perfect. The kids zone has different sections, and the section I would like to disable is the VLOGLab section. So we could actually have our own Kids Zone, and a Kids Zone settings section where one could enable/disable these sections.

Hmmm, the VLOGLab stuff is also featured in the "VTM KIDS" section, so that needs to be disabled as well. Let's first see what information we get back...

**Comment by michaelarnauts** [comment]
Kids mode was easy. It is just a different endpoint with the same api's. 

See #44 for a basic implementation. It adds a setting and a menu item to easily switch between the modes.

**Comment by michaelarnauts** [comment]
@dagwieers 

For this implementation, I would prefer to have this all in settings. I've added a "Kids Mode" category where an item could be added that fetches all the categories and put it in a `multiselect` where you can select or unselect categories. By default, they are all selected and you can unselect the ones you don't like. These could be saved in a hidden setting and parsed when viewing the category view in kids mode.

**Comment by dagwieers** [comment]
That's exactly what I had in mind. Although I was thinking of reading/writing a JSON file.
We already have this code in place for VRT.NU (where you can "follow" or "unfollow" a program).

**Comment by dagwieers** [comment]
I contacted VTM GO regarding the series they have in the Kids zone, and they insist that what they have approved for the Kids zone should be fine. But we don't agree that this is intended for Kids (all ages). So this functionality is still very much needed.
