### ISSUE TITLE
Add PG information to plot

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#43]
Currently we have access to PG information but we don't expose it to the user.
Possibly if this works fine, we could limit the add-on to only show content that fits user's PG requirements.

This relates to #38, but does not fix the desire to exclude specific shows that *do* fit PG requirements but are unwanted based on content/context.

**Comment by michaelarnauts** [comment]
I like the ability to filter based on PG information, but maybe only as an setting in the kids mode?

**Comment by dagwieers** [comment]
After adding it to the add-on, I can only find **PP** (Product Placement) tags.
So I think the Parental Guidance only really applies to movies :-(

**Comment by dagwieers** [comment]
Closed by #45
