### ISSUE TITLE
Add support for "Up Next"

### ISSUE THREAD

**Issue by michaelarnauts** [michaelarnauts/plugin.video.vtm.go#49]
The "Up Next" Kodi addon provides netflix-like binge watching features. When an episode is finished, it can show a message to play the next episode. This works since an addon can emit a message with the information about the next episode.

More information is available here: https://forum.kodi.tv/showthread.php?tid=336747

Information on how to integrate is here: https://github.com/im85288/service.upnext/wiki/Addon-Integration

**Comment by dagwieers** [comment]
The kids are so used to it now on VRT NU, that it would be really nice to have this for VTM GO too.

**Comment by dagwieers** [comment]
It would be good to take this opportunity to evaluate the documentation in the Wiki. It is lacking in many ways, but a fresh look from a new developer always helps to find issues.

**Comment by michaelarnauts** [comment]
The new api directly provides information and the playableId of the next episode when fetching details of a specific episode.
