### ISSUE TITLE
Implement additional catalogue sections

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#93]
The VTM GO app has the following sections missing from the catalogue:
- Nieuw op VTM GO
- VTM pakt groots uit!
- Criminele Goeie Series
- Populair op VTM GO
- Bingewaardig

It would be nice to have these as well.

**Comment by dagwieers** [comment]
These are actually not in the catalogue, but sections on the app's main entrance page

**Comment by michaelarnauts** [comment]
Those are available in the object returned from get_main. The sections are dynamic and can change.
