### ISSUE TITLE
Allow hiding specific items from the main menu

### ISSUE THREAD

**Issue by michaelarnauts** [michaelarnauts/plugin.video.vtm.go#97]
Provide checkboxes in the settings to be able to hide the following items:
* A-Z
* Catalogue
* Live TV
* TV Guide
* Recommendations
* My List
* Youtube
* Search

By default, everything is shown. Maybe the Kids zone settings should also move here, since there is also an option to hide it there.

**Comment by dagwieers** [comment]
IMO the current **Live TV**, **Youtube** and **TV guide** entries belong into a single **Channels** menu entry, which would list the programs from that channel together with a Live TV, a Youtube and a TV guide entry. This would be the channel-centric view.

And the TV guide would become a calendar-based view, so it is easier to switch between channels for the same (e.g. current) day. Now you have to go back 2 times, and then select the next channel, and again select the same day. That's a lot of clicks for basically switching between channels. (Hence why we designed it like that for VRT NU).

**Comment by michaelarnauts** [comment]
@dagwieers I did this in #114 

I still plan to add toggles to hide:
* Recommendations
* My list
* Kids mode
